analysis:
  complexity_analysis: true
  dependency_analysis: true
  language_detection: true
  metrics_calculation: true

cleaning:
  normalize_whitespace: false
  preserve_structure: true
  remove_blank_lines: false
  remove_comments: false
  remove_imports: false

deduplication:
  hash_algorithm: sha256
  min_file_size: 100
  similarity_threshold: 0.95

extraction:
  exclude_dirs:
  - .git
  - __pycache__
  - node_modules
  - .venv
  - venv
  - build
  - dist
  - target
  - .idea
  - .vscode
  - .DS_Store
  exclude_files:
  - .gitignore
  - .gitattributes
  - README.md
  - LICENSE
  - package-lock.json
  - yarn.lock
  - Pipfile.lock
  file_types:
  - .py
  - .js
  - .ts
  - .java
  - .cpp
  - .c
  - .h
  - .go
  - .rs
  - .php
  - .rb
  - .swift
  - .kt
  - .cs
  - .scala
  - .r
  - .m
  - .sh
  - .sql
  - .html
  - .css
  - .xml
  - .json
  - .yaml
  - .yml
  - .md
  - .txt
  max_file_size: 20971520

file_metrics_cleaning:
  thresholds:
    max_average_line_length: 200
    max_comment_percentage: 50
    max_digit_percentage: 50
    max_file_size: 1048576
    max_hex_percentage: 30
    max_line_count: 10000
    max_line_length: 500
    min_comment_percentage: 0

jsonl_cleaning:
  enable_comment_cleaning: true
  enable_desensitization: true
  invalid_comment_patterns:
  - todo
  - fixme
  - version_info
  - personal_signature
  - change_history
  preserve_copyright_structure: true
  remove_invalid_comments: true
  sensitive_patterns:
  - email
  - phone
  - employee_id
  - id_card
  - ip_address
  - url
  - datetime
  - person_name
  - organization

pipeline:
  # 默认pipeline配置
  default_pipeline: "standard"
  pipelines:
    # 标准pipeline：提取 -> 去重 -> 内容清洗 -> 文件清洗
    standard:
      name: "标准数据处理流程"
      description: "完整的代码仓库数据处理流程"
      steps:
        - name: "extract"
          type: "extractor"
          enabled: true
          config:
            output_format: "jsonl"
            include_metadata: true
        - name: "content_clean"
          type: "cleaner"
          enabled: true
          depends_on: ["extract"]
          config:
            method: "content_cleaning"
            preserve_structure: true
        - name: "metrics_clean"
          type: "cleaner"
          enabled: true
          depends_on: ["content_clean"]
          config:
            method: "file_metrics_cleaning"
            remove_violations: true
        - name: "deduplicate"
          type: "cleaner"
          enabled: true
          depends_on: ["metrics_clean"]
          config:
            method: "deduplication"
            keep_strategy: "newest"

    # 快速pipeline：只提取和去重
    quick:
      name: "快速处理流程"
      description: "仅进行文件提取和去重"
      steps:
        - name: "extract"
          type: "extractor"
          enabled: true
          config:
            output_format: "jsonl"
        - name: "deduplicate"
          type: "cleaner"
          enabled: true
          depends_on: ["extract"]
          config:
            method: "deduplication"
    # 深度清洗pipeline：包含所有清洗步骤
    deep_clean:
      name: "深度清洗流程"
      description: "包含所有清洗步骤的完整流程"
      steps:
        - name: "extract"
          type: "extractor"
          enabled: true
          config:
            output_format: "jsonl"
            include_metadata: true
        - name: "deduplicate"
          type: "cleaner"
          enabled: true
          depends_on: ["extract"]
          config:
            method: "deduplication"
            keep_strategy: "newest"
        - name: "content_clean"
          type: "cleaner"
          enabled: true
          depends_on: ["deduplicate"]
          config:
            method: "content_cleaning"
            remove_comments: true
            remove_imports: true
            normalize_whitespace: true
        - name: "jsonl_clean"
          type: "cleaner"
          enabled: true
          depends_on: ["content_clean"]
          config:
            method: "jsonl_cleaning"
            enable_comment_cleaning: true
            enable_desensitization: true
        - name: "metrics_clean"
          type: "cleaner"
          enabled: true
          depends_on: ["jsonl_clean"]
          config:
            method: "file_metrics_cleaning"
            remove_violations: true
    # 分析pipeline：只分析不修改
    analysis:
      name: "分析流程"
      description: "仅进行分析，不修改文件"
      steps:
        - name: "extract"
          type: "extractor"
          enabled: true
          config:
            output_format: "jsonl"
            include_metadata: true
        - name: "analyze_duplicates"
          type: "analyzer"
          enabled: true
          depends_on: ["extract"]
          config:
            method: "duplicate_analysis"
        - name: "analyze_metrics"
          type: "analyzer"
          enabled: true
          depends_on: ["extract"]
          config:
            method: "metrics_analysis"

logging:
  backup_count: 5
  file: data/logs/repodp.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10485760

performance:
  batch_size: 100
  max_workers: 8
  memory_limit: 1024
  timeout: 300

reporting:
  default_format: comprehensive
  output_dir: data/reports
  supported_formats:
  - json
  - csv
  - html
  - markdown
  - comprehensive
